import os, sys
import shutil
import subprocess
#import numpy as np # only required for setting fft value

#===========================================================================================================#
# ----------------------------------------- Start of Functions ---------------------------------------------#
#===========================================================================================================#

def mol2pdb(outdir, inp, segid, resid):
	ligXYZ = {}
	#segid = 'LIG'
	#resid = 'MOL'
	resid = int(resid)
	fp = open(f'{inp}.mol2', 'r')

	line=fp.readline()
	while line:
		if line[0:13] == '@<TRIPOS>ATOM':
			line=fp.readline()
			while line[0:13] != '@<TRIPOS>BOND':
				lns=line.split()
				ligXYZ[lns[1]]=lns[2:5]
				#print(ligXYZ)
				line=fp.readline()
			break
		else:
			line=fp.readline()
	fp.close()

	fp=open(f'{outdir}/{inp}.pdb','w')
	row = 0
	for at in ligXYZ:
		row+=1 
		fp.write("ATOM  %5d %-4s %4s%5d    %8.3f%8.3f%8.3f%6.2f%6.2f      %-4s\n" % (\
				row,at,segid,resid,float(ligXYZ[at][0]),float(ligXYZ[at][1]),float(ligXYZ[at][2]),1,0,segid))

	fp.write("TER\nEND")
	fp.close()
	
def change_rtf(outdir, inp, ext, resname):
	fp = open(f'{inp}{ext}', 'r') 
	fout = open(f'{outdir}/{inp}{ext}','w') 

	for line in fp:
		if line.startswith('RESI'):
			l = line.split()
			l[1] = str(resname)
			fout.write(' '.join(l) + '\n')
			#print(l)
		else:
			fout.write(line)

	fp.close()
	fout.close()

##***************************************************************
##*************** Charlie's Function ****************************
# Ensure that FFT grid is product of small primes 2, 3, 5
def is_factor(n):
	if (n % 2 != 0): return False  # favors even number
	while n:
		flag = False
		for x in (2,3,5):
			if n % x == 0:
				n = n / x
				flag = True
				break

		if flag: continue
		break

	if n == 1: return True
	return False

def checkfft(n, margin = 5):
	n = int(n) + margin
	while 1:
		if is_factor(n): break
		else: n += 1
	return n
##***************************************************************

##***************************************************************
##******************** From msld_wrt.py *************************
def write_charmm_inp(sysname, outdir, mol_list, rtfs=False, dum=False, cgenff=True):

	# load in nsubs/nsites
	fp=open(outdir+'/nsubs','r')
	nsubs=[]
	for sub in fp.readline().split():
	    nsubs.append(int(sub))
	nsites=len(nsubs)
	fp.close()

	# some default variables:
	fnex = 5.5
	cats = True # info not used anywhere for now.

	# write n* files (nsubs, nblocks, & nreps)
	fp=open(outdir+'/name','w')
	fp.write('%s' % (sysname))
	fp.close()
	fp=open(outdir+'/nnodes','w')
	fp.write('1')
	fp.close()
	fp=open(outdir+'/ncentral','w')
	fp.write('0')
	fp.close()

	# write CHARMM scripts
	# (1) ALF/CHARMM scripts first (mostly copied from process)
	fp=open(outdir+"/"+sysname+".inp","w")

	fp.write("* CHARMM input file for Multi-Site lambda-dynamics\n")
	fp.write("* generated by py_prep (JZV 02/2019) for ALF (RLH 01/2019)\n")
	fp.write("*\n")
	fp.write("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n")
	fp.write("!  Multi-Site Lambda Dynamics \n")
	fp.write("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\n")

	fp.write("set fnex = %s \n" % (fnex))
	fp.write("set builddir = prep\n")
	fp.write("set box = ????\n")
	fp.write("set fft = ????\n")
	fp.write("set temp = 298.15\n\n")

	fp.write("! perturbation variables\n")
	fp.write("set nsites = %d \n" % (len(nsubs)))
	for sub in range(len(nsubs)):
	  fp.write("set nsubs%d = %d \n" % (sub+1,nsubs[sub]))
	fp.write("set nblocks = %d \n\n" % (sum(nsubs)))

	fp.write("bomblev -2\n\n")

	fp.write("!! Read in toppar stream file\n")
	fp.write("stream @builddir/toppar.str\n\n")
	
	fp.write("!! !! Reads coordinates and pdb file for the protein\n")

	fp.write("\n")
	fp.write("!! !! Read ligand toppar and pdb files for generating segments and coordinates \n")
	# move onto the ligand
	nmol = 1
	for mol in mol_list:
		if rtfs == False:
			fp.write(f"stream @builddir/{mol}.str \n")
		else:
			if cgenff == True:
				fp.write(f"read rtf append card name @builddir/{mol}.rtf \n")
				fp.write(f"read param flex append card name @builddir/{mol}.prm \n\n")

		fp.write(f"read sequ pdb name @builddir/{mol}.pdb \n")
		fp.write(f"generate ML{nmol} setup first none last none \n")
		fp.write(f"read coor pdb name @builddir/{mol}.pdb \n\n")

		fp.write(f"ic generate \n")
		fp.write(f"ic param \n")
		fp.write(f"ic build \n")
		fp.write(f"define LONEPAIR sele chem LPH end \n")
		fp.write(f"if ?nsel .gt. 0 coor shake sele LONEPAIR end \n")
		fp.write(f"prnlev 0 \n")
		fp.write(f"hbuild sele hydr end \n")
		fp.write(f"prnlev 5 \n\n")
		fp.write(f"! check if there are unknown coordinate \n")
		fp.write(f"define XXX sele .not. INIT show end \n")
		fp.write(f"if ?nsel .gt. 0 stop ! ABNORMAL TERMINATION: Undefined coordinates \n\n")
		nmol +=1

	fp.write("!! Define MSLD substituent selections\n")
	if dum == True:
		fp.write(f"define site1_sub1 sele resname dum show end \n")
		for nmols in range(len(mol_list)):
			fp.write(f"define site1_sub{nmols+2} sele resname LG{nmols+1} show end \n")
	else:
		for nmols in range(len(mol_list)):
			fp.write(f"define site1_sub{nmols+1} sele resname LG{nmols+1} show end \n")
	fp.write("\n")

	# auto angles and dihedrals b/c msld_*.py scripts don't calculate them
	fp.write("auto angle dihe  !! do not call after deleting sub-sub terms or loading in water\n")
	fp.write("bomblev -1\n\n")

	# new: remove angles and dihedrals between substituents at the same site
	fp.write("! delete angles and dihedrals between alchem groups\n")
	fp.write("set ii = 1\n")
	fp.write("label deletesiteloop\n")
	fp.write("if @ii .le. @nsites then\n\n")
	fp.write("   set jj = 1\n")
	fp.write("   label delete1loop\n")
	fp.write("   if @jj .le. @nsubs@@ii then\n\n")
	fp.write("      calc kk = @jj + 1\n")
	fp.write("      label delete2loop\n")
	fp.write("      if @kk .le. @nsubs@@ii then\n\n")
	fp.write("         dele connectivity sele ( site@{ii}_sub@@jj ) show end sele ( site@{ii}_sub@@kk ) show end\n")
	#fp.write("         dele angle sele ( site@{ii}_sub@@jj ) show end sele ( site@{ii}_sub@@kk ) show end\n")
	#fp.write("         dele dihe  sele ( site@{ii}_sub@@jj ) show end sele ( site@{ii}_sub@@kk ) show end\n")
	#fp.write("         dele impr  sele ( site@{ii}_sub@@jj ) show end sele ( site@{ii}_sub@@kk ) show end\n\n")
	fp.write("         calc kk = @kk + 1\n")
	fp.write("         goto delete2loop\n")
	fp.write("      endif\n\n")
	fp.write("      calc jj = @jj + 1\n")
	fp.write("      goto delete1loop\n")
	fp.write("   endif\n\n")
	fp.write("   calc ii = @ii + 1\n")
	fp.write("   goto deletesiteloop\n")
	fp.write("endif\n\n")

	fp.write("!! ! System specific deletion (linear groups)\n")
	fp.write("!! dele dihe sele (atom LIG 1 ATOMNAME) show end\n\n")

	fp.write("!! coor orient\n\n")

	fp.write("!! Load solvent\n")
	fp.write("read sequ pdb name @builddir/solvent.pdb\n")
	fp.write("generate WT00 first none last none setup noangl nodihe\n")
	fp.write("read coor pdb resid name @builddir/solvent.pdb\n\n")

	fp.write("!! !! Load ions\n")
	fp.write("!! read sequ pdb name @builddir/ions.pdb\n")
	fp.write("!! generate HETA first none last none setup noangl nodihe\n")
	fp.write("!! read coor pdb resid name @builddir/ions.pdb\n\n")

	fp.write("print coor sele .not. init end\n\n")
	fp.write("bomblev 0\n\n")

	fp.write("!! !! Write Initial System to Disk\n")
	fp.write("!! write psf card name patch.psf\n")
	fp.write("!! * patch psf file\n")
	fp.write("!! *\n")
	fp.write("!! write coor pdb card name patch.pdb\n")
	fp.write("!! * patch pdb file\n")
	fp.write("!! *\n")
	fp.write("!! write coor card name patch.crd\n")
	fp.write("!! * patch crd file\n")
	fp.write("!! *\n\n")
    
	fp.write("!! Create water box & periodic images\n")
	fp.write("coor stat\n")
	fp.write("crystal define cubic @box @box @box 90. 90. 90.\n")
	fp.write("crystal build cutoff 14 nope 0\n")
	fp.write("image byres xcen 0 ycen 0 zcen 0 sele resn tip3 .or. resn sod .or. resn pot .or. resn cla end\n")
	fp.write("image byseg xcen 0 ycen 0 zcen 0 sele .not. ( resn tip3 .or. resn sod .or. resn pot .or. resn cla ) end\n\n")
	fp.write("!! Copy main coords into comp set\n")
	fp.write("cons harm clear\ncoor copy comp\n\n")

	fp.write("! LDBI math: for every \"pair\" there are 5 ldbi's\n")
	fp.write("set ii = 1\n")
	fp.write("set ldbibias = 0\n")
	fp.write("label ldbimathloop\n")
	fp.write("if @ii .le. @nsites then\n")
	fp.write("   calc ldbibias = @ldbibias + ( ( @nsubs@@ii * (@nsubs@@ii - 1) / 2 ) * 5 )\n")
	fp.write("   INCR ii by 1\n")
	fp.write("   goto ldbimathloop\n")
	fp.write("endif\n")
	fp.write("set charge = ?cgtot\n\n")
	fp.write("calc blockplusone = @nblocks + 1\n\n")

	fp.write("!! BLOCK setup\n")
	fp.write("BLOCK @blockplusone\n")
	fp.write("   clear\n")
	fp.write("END\n")

	fp.write("BLOCK @blockplusone !RX! NREP @nreps\n")
	if dum == True:
		fp.write(f"   Call 2 sele site1_sub1 show end \n")
		for nmols in range(len(mol_list)):
			fp.write(f"   Call {nmols+3} sele site1_sub{nmols+2} show end \n")
	else:
		for nmols in range(len(mol_list)):
			fp.write(f"   Call {nmols+2} sele site1_sub{nmols+1} show end \n")
	fp.write("\n")
	fp.write("   qldm theta\n")
	fp.write("   lang temp @temp\n")
	fp.write("   !RX! phmd ph 7\n")
	fp.write("   soft on   ! this turns on soft-cores\n")
	fp.write("   pmel ex   ! this turns on PME\n\n")
	fp.write("   ldin 1 1.0  0.0  5.0  0.0  5.0\n")
	Block=1
	for Site in range(1,nsites+1):
		for Sub in range(1,nsubs[Site-1]+1):
			Block+=1
			if Sub == 1:
				fp.write("   ldin %-2d %.4f 0.0  5.0  @lams%ds%d 5.0 !RX! NONE\n" % (Block,1.0/nsubs[Site-1],Site,Sub))
			elif Sub % 2:
				fp.write("   ldin %-2d %.4f 0.0  5.0  @lams%ds%d 5.0 !RX! UPOS 7.0\n" % (Block,1.0/nsubs[Site-1],Site,Sub))
			else:
				fp.write("   ldin %-2d %.4f 0.0  5.0  @lams%ds%d 5.0 !RX! UNEG 7.0\n" % (Block,1.0/nsubs[Site-1],Site,Sub))
	fp.write("\n")

	fp.write("   set si = 1 \n")
	fp.write("   label ex_si_loop \n")
	fp.write("   if @si .le. @nsites then \n")
	fp.write("      set ii = 1 \n")
	fp.write("      label ex_ii_loop \n")
	fp.write("      if @ii .le. @nsubs@@si then \n")
	fp.write("         calc jj = @ii + 1 \n")
	fp.write("         label ex_jj_loop \n")
	fp.write("         if @jj .le. @nsubs@@si then \n")
	fp.write("            calc iip1 = @ii + 1 \n")
	fp.write("            calc jjp1 = @jj + 1 \n")
	fp.write("            adex @iip1 @jjp1 \n")
	fp.write("            calc jj = @jj + 1 \n")
	fp.write("            goto ex_jj_loop \n")
	fp.write("         endif \n")
	fp.write("         calc ii = @ii + 1 \n")
	fp.write("         goto ex_ii_loop \n")
	fp.write("      endif \n")
	fp.write("      calc si = @si + 1 \n")
	fp.write("      goto ex_si_loop \n")
	fp.write("   endif	 \n\n")

	fp.write("   !!rmla bond thet dihe impr \n")
	fp.write("   rmla bond thet impr \n")
	fp.write("   msld 0")
	for Site in range(1,len(nsubs)+1):
		for Sub in range(1,nsubs[Site-1]+1):
			fp.write("  %d" % (Site,))
	fp.write("  fnex @fnex\n")
	fp.write("   msma\n")
	fp.write("   thbv inde all auto \n\n") 

	fp.write("   scat on\n")
	fp.write("   scat k 118.4\n\n")

	fp.write("   stream @builddir/cats_selection.inp\n\n")

	# New way:
	fp.write("   ! Check block.doc for functional form of these biasing potentials\n")
	fp.write("   calc nbiaspot = 5 * ( @nblocks * ( @nblocks - 1 ) ) / 2\n")
	fp.write("   ldbi @nbiaspot\n")
	fp.write("   set ibias = 1\n")
	fp.write("   set iblock = 0\n")
	fp.write("   set si = 1\n")
	fp.write("   label loop5_vb\n")
	fp.write("   if @si .le. @nsites then\n")
	fp.write("      set jblock = @iblock\n")
	fp.write("      set sj = @si\n")
	fp.write("      label loop5b_vb\n")
	fp.write("      if @sj .le. @nsites then\n")
	fp.write("         set ii = 1\n")
	fp.write("         label loop6_vb\n")
	fp.write("         if @ii .le. @nsubs@@{si} then\n")
	fp.write("            calc ip1 = @ii + 1 + @iblock\n")
	fp.write("            set jj = 1\n")
	fp.write("            if @si .eq. @sj then\n")
	fp.write("               calc jj = @ii + 1\n")
	fp.write("            endif\n")
	fp.write("            label loop7_vb\n")
	fp.write("            if @jj .le. @nsubs@@{sj} then\n")
	fp.write("               calc jp1 = @jj + 1 + @jblock\n")
	fp.write("   \n")
	fp.write("               set c_shift = 0.0\n")
	fp.write("               set x_shift = 0.0\n")
	fp.write("               set s_shift = 0.0\n")
	fp.write("               !vbrex! if @si .eq. @sj then\n")
	fp.write("               !vbrex!    calc c_shift = 1.2 * (@myrep - @ncentral)\n")
	fp.write("               !vbrex!    calc s_shift = 0.3 * (@myrep - @ncentral)\n")
	fp.write("               !vbrex! endif\n")
	fp.write("   \n")
	fp.write("               calc coeff = @cs@@{si}s@@{ii}s@@{sj}s@@{jj} + @{c_shift}\n")
	fp.write("               ldbv @ibias @ip1 @jp1 6 0.0 @coeff 0\n")
	fp.write("               calc ibias = @ibias + 1\n")
	fp.write("               calc coeff = @xs@@{si}s@@{ii}s@@{sj}s@@{jj} + @{x_shift}\n")
	fp.write("               ldbv @ibias @ip1 @jp1 10 -5.56 @coeff 0\n")
	fp.write("               calc ibias = @ibias + 1\n")
	fp.write("               calc coeff = @ss@@{si}s@@{ii}s@@{sj}s@@{jj} + @{s_shift}\n")
	fp.write("               ldbv @ibias @ip1 @jp1 8 0.017 @coeff 0\n")
	fp.write("               calc ibias = @ibias + 1\n")
	fp.write("               calc coeff = @xs@@{sj}s@@{jj}s@@{si}s@@{ii} + @{x_shift}\n")
	fp.write("               ldbv @ibias @jp1 @ip1 10 -5.56 @coeff 0\n")
	fp.write("               calc ibias = @ibias + 1\n")
	fp.write("               calc coeff = @ss@@{sj}s@@{jj}s@@{si}s@@{ii} + @{s_shift}\n")
	fp.write("               ldbv @ibias @jp1 @ip1 8 0.017 @coeff 0\n")
	fp.write("               calc ibias = @ibias + 1\n")
	fp.write("               calc jj = @jj + 1\n")
	fp.write("               goto loop7_vb\n")
	fp.write("            endif\n")
	fp.write("            calc ii = @ii + 1\n")
	fp.write("            goto loop6_vb\n")
	fp.write("         endif\n")
	fp.write("         calc jblock = @jblock + @nsubs@@{sj}\n")
	fp.write("         calc sj = @sj + 1\n")
	fp.write("         goto loop5b_vb\n")
	fp.write("      endif\n")
	fp.write("      calc iblock = @iblock + @nsubs@@{si}\n")
	fp.write("      calc si = @si + 1\n")
	fp.write("      goto loop5_vb\n")
	fp.write("   endif\n")

	fp.write("END\n\n")

	# turn off NOEs by default - makes more user customizable
	fp.write("!! !! Set NOE distance restraints\n")
	fp.write("!! NOE\n")
	fp.write("!!    RESET\n")
	fp.write("!! END\n")
	fp.write("!! \n")
	fp.write("!! faster on\n")
	fp.write("!! !! set up energy parameters if you want to use NOEs\n")
	fp.write("!! nbonds atom fswitch vdw vfswitch cdie eps 1 -\n")
	fp.write("!!     cutnb 14.0 cutim 14.0 ctonnb 10.0 ctofnb 12.0\n\n")
	fp.write("!! energy\n")
	fp.write("!! NOE\n")
	for Site in range(1,len(nsubs)+1):
		fp.write("!! ! Site %d\n" % (Site,))
	for Sub in range(2,nsubs[Site-1]+1):
		fp.write("!!    assign sele atom LIG 1 %s end sele atom LIG 1 %s end -\n" % ("Atom1","Atom2"))
		fp.write("!!    kmin 1.0 rmin 0.0 kmax 1.0 rmax 0.2 fmax 2.0 rswitch 2.0 sexp 1.0\n")
		break
	fp.write("!! \n")
	fp.write("!!    print anal\n")
	fp.write("!! END\n\n\n")

	# (1) Finished
	fp.close()


def largest_ligand(outdir, mol_list):
	natoms = []
	for mol in mol_list:
		#natoms.append(os.system(f"grep -i atom {outdir}/{mol}.pdb | wc -l "))
		with open(f'{outdir}/{mol}.pdb') as f2:
			count = sum(1 for line in f2 if "ATOM" in line.upper())
		natoms.append(count)
	max_idx = natoms.index(max(natoms))
	#os.system(f"cp {outdir}/{mol_list[max_idx]}.pdb {outdir}/large_lig.pdb")
	shutil.copyfile(f"{outdir}/{mol_list[max_idx]}.pdb", f"{outdir}/large_lig.pdb")
	

#===========================================================================================================#
# -------------------------------- End of Functions --------------------------------------------------------#
#===========================================================================================================#

## Required files
## Mol2 Files, str (or rtf, prm) files, mol_list.txt
## Use some script to generate selections for CATS (segid will be ML**, resnames will be LG**)
##

#===================================================================
#------------------- user inputs ----------------------------------
sysname = 'tpsb'
outdir = f'build.{sysname}' 
mol_list = 'mol_list.txt'
dummy = True
rtfs = False # are we working with str files or rtf files
cgenff = True

## to do list:

#==================================================================
if rtfs == True:
	if cgenff == True:
		ext = '.rtf'
	else:
		ext = '_charmm.rtf'
else:
	ext = '.str'

## Step 1. Write some general information files
os.system(f"mkdir -p {outdir}")	

with open(mol_list, 'r') as f0:
	if dummy == True:
		nmols = len(f0.readlines()) + 1
	else:
		nmols = len(f0.readlines())
	fp = open(f'{outdir}/nsubs', 'w')
	fp.write(str(nmols))
	fp.close()
	fp = open(f'{outdir}/nblocks', 'w')
	fp.write(str(nmols))
	fp.close()
f0.close()

## Step 2. Convert the mol2 files to pdb files
mols_list = []
mol = 0
with open(mol_list, 'r') as f0:
	for lines in f0.readlines():
		mol_name = str(lines.split('\n')[0]).split(' ')[0]
		mols_list.append(mol_name)
		mol2pdb(outdir, mol_name, f'LG{mol+1}', f'{mol+1}') # hardcoded LG here but appending 1,2,3...
		change_rtf(outdir, mol_name, ext, f'LG{mol+1}') # hardcoded LG here
		mol += 1
	f0.close()

largest_ligand(outdir, mol_list=mols_list)

## Step 3. Write the CHARMM input script
write_charmm_inp(sysname, outdir, mol_list=mols_list, rtfs=rtfs, dum=dummy, cgenff=cgenff)
if rtfs == True:
    os.system(f'cp *.prm {outdir}/')
if cgenff == False:
	os.system(f'python opls_ld_rtf_prm_v2.py {outdir}')

'''
## Step 4. Solvation with MMTSB and generating a new directory
## check if we need to add any ions in the solvent side
inpdir = outdir
outdir = 'solv_prep'
cutoff = 12

print(f"Using a solvate cutoff of {cutoff}")
##os.system(f"mkdir -p {outdir}")

os.system(f"cp -r {inpdir} {outdir}")
os.system(f"convpdb.pl -solvate -cubic -cutoff {cutoff} {inpdir}/large_lig.pdb > {outdir}/solvated.pdb 2> hydration.log")
###cmd1 = f"""awk 'BEGIN {{CC=0}} {{if ($1=="ATOM" && $2==1) {{if (CC==0) {{CC=1; X=$6; Y=$7; Z=$8}} else {{print X-$6, Y-$7, Z-$8}}}}}}' {outdir}/solvated.pdb {inpdir}/large_lig.pdb"""
cmd1 = f"""awk 'BEGIN {{CC=0}} {{if ($1=="ATOM" && $2==1) {{if (CC==0) {{CC=1; X=$6; Y=$7; Z=$8}} else {{print X-$6, Y-$7, Z-$8}}}}}}' {inpdir}/large_lig.pdb {outdir}/solvated.pdb"""
XYZ = subprocess.run(cmd1, shell=True, capture_output=True, text=True, check=True).stdout.strip()
os.system(f"convpdb.pl -translate {XYZ} -segnames {outdir}/solvated.pdb > {outdir}/translated.pdb")
os.system(f"convpdb.pl -segnames -nsel TIP3 {outdir}/translated.pdb > {outdir}/solvent.pdb")
os.system(f"rm {outdir}/solvated.pdb {outdir}/translated.pdb ")
'''
quit()

os.system("bash Lg_Solvate_charged.sh 2> hydration.log")

with open('hydration.log', 'r') as f11:
	for line in f11.readlines():
		box_size = float(line.split()[2])
		break

fft = checkfft(n=box_size, margin=0)
print(fft)

quit()
##os.system(f"cp {outdir}/{sysname}.inp {outdir}/{sysname}.inp.0")
os.system(f"sed -i 's/set box = ????/set box = {box_size}/g' {outdir}/{sysname}.inp")
os.system(f"sed -i 's/set fft = ????/set fft = {fft}/g' {outdir}/{sysname}.inp")

quit()
